WEB_INGESTION_SOURCES = [
    {
        "provider": "BambooHR",
        "source_name": "BambooHR Help Center - Time Off",
        "root_url": "https://help.bamboohr.com/",
        "category": "time_off",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 20,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "time off",
            "vacation",
            "leave",
            "pto",
            "holiday",
            "approval",
            "manager",
            "employee",
            "request",
            "balance",
            "accrual",
        ],
        "seed_urls": [
            "https://help.bamboohr.com/s/article/640810",
            "https://help.bamboohr.com/s/article/788839",
            "https://help.bamboohr.com/s/article/588028",
        ],
    },
    {
        "provider": "Gusto",
        "source_name": "Gusto Support - Payroll and Time Off",
        "root_url": "https://support.gusto.com/",
        "category": "payroll_time_off",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 24,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "payroll",
            "time off",
            "benefits",
            "employee",
            "manager",
            "policy",
            "request",
            "approval",
            "sick time",
            "vacation",
            "tax",
            "payment",
        ],
        "seed_urls": [
            "https://support.gusto.com/article/999877041000000/request-and-manage-time-off-for-employees",
            "https://support.gusto.com/article/999756591000000/set-up-and-manage-time-off-policies-for-admins",
            "https://support.gusto.com/article/100395028100000/turn-on-and-manage-employee-time-off-requests-for-admins",
            "https://support.gusto.com/article/101980064100000/approve-and-edit-time-off-requests-for-managers",
        ],
    },
    {
        "provider": "Personio",
        "source_name": "Personio Help Center - HR Workflows",
        "root_url": "https://support.personio.de/hc/en-us",
        "category": "hr_workflows",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 20,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "onboarding",
            "offboarding",
            "absence",
            "employee",
            "approval",
            "roles",
            "permissions",
            "workflow",
            "documents",
            "performance",
        ],
        "seed_urls": [
            "https://support.personio.de/hc/en-us/articles/115002474325-Common-onboarding-templates-and-steps",
            "https://www.personio.com/product/onboarding/",
            "https://www.personio.com/product/absence-management/",
            "https://www.personio.com/product/approval-processes/",
        ],
    },
    {
        "provider": "Factorial",
        "source_name": "Factorial Help Center - Workflows and Approvals",
        "root_url": "https://help.factorialhr.com/en_US/",
        "category": "workflow_automation",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 24,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "onboarding",
            "offboarding",
            "workflow",
            "automation",
            "time off",
            "absence",
            "approval",
            "approver",
            "employee",
            "task",
            "permissions",
        ],
        "seed_urls": [
            "https://help.factorialhr.com/en_US/workflows-automations/onboarding-workflow",
            "https://help.factorialhr.com/en_US/workflows-automations/about-the-offboarding-workflow",
            "https://help.factorialhr.com/en_US/absences-approvals/how-to-create-time-off-approval-systems",
        ],
    },
    {
        "provider": "Deel",
        "source_name": "Deel Help Center - Employee Lifecycle",
        "root_url": "https://help.letsdeel.com/hc/en-gb",
        "category": "global_hr_lifecycle",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 16,
        "min_urls": 3,
        "extract_depth": "advanced",
        "keywords": [
            "onboarding",
            "offboarding",
            "time off",
            "pto",
            "employee",
            "worker",
            "documents",
            "leave",
            "policy",
            "global",
        ],
        "seed_urls": [
            "https://help.letsdeel.com/hc/en-gb/articles/4407737623825-Employee-Onboarding-Guide",
            "https://www.deel.com/glossary/offboarding/",
        ],
    },
    {
        "provider": "Rippling",
        "source_name": "Rippling HR Operations References",
        "root_url": "https://www.rippling.com/",
        "category": "hr_it_operations",
        "source_type": "web_hr_saas_reference",
        "use_map": True,
        "max_depth": 1,
        "max_urls": 12,
        "min_urls": 2,
        "extract_depth": "advanced",
        "keywords": [
            "onboarding",
            "offboarding",
            "permissions",
            "approval",
            "time off",
            "payroll",
            "employee",
            "workflow",
            "access",
            "lifecycle",
        ],
        "seed_urls": [
            "https://www.rippling.com/platform/permissions",
            "https://www.rippling.com/blog/leave-management",
            "https://www.rippling.com/blog/hr-system-switch-survival-guide",
        ],
    },
    {
        "provider": "SHRM",
        "source_name": "SHRM HR Policies",
        "root_url": "https://www.shrm.org/topics-tools/tools/policies",
        "category": "hr_policy_reference",
        "source_type": "web_hr_policy_reference",
        "use_map": True,
        "max_depth": 1,
        "max_urls": 12,
        "min_urls": 3,
        "extract_depth": "advanced",
        "keywords": [
            "policy",
            "leave",
            "vacation",
            "sick",
            "benefits",
            "employment",
            "workplace",
            "harassment",
            "overtime",
        ],
        "seed_urls": [
            "https://www.shrm.org/topics-tools/tools/policies",
            "https://www.shrm.org/topics-tools/employment-law-compliance/reduce-sick-leave-abuse",
            "https://www.shrm.org/topics-tools/employment-law-compliance/viewpoint-implement-global-policies-not-global-handbook",
        ],
    },
]