WEB_INGESTION_SOURCES = [
    {
        "provider": "BambooHR",
        "source_name": "BambooHR Help Center - Time Off",
        "root_url": "https://help.bamboohr.com/",
        "category": "time_off",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 20,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "time off",
            "vacation",
            "leave",
            "pto",
            "holiday",
            "approval",
            "manager",
            "employee",
            "request",
            "balance",
            "accrual",
        ],
        "seed_urls": [
            "https://help.bamboohr.com/s/article/640810",
            "https://help.bamboohr.com/s/article/788839",
        ],
    },
    {
        "provider": "Gusto",
        "source_name": "Gusto Support - Payroll and Time Off",
        "root_url": "https://support.gusto.com/",
        "category": "payroll_time_off",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 20,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "payroll",
            "time off",
            "benefits",
            "employee",
            "manager",
            "policy",
            "request",
            "approval",
            "sick time",
            "vacation",
            "tax",
            "payment",
        ],
        "seed_urls": [
            "https://support.gusto.com/article/999877041000000/request-and-manage-time-off-for-employees",
            "https://support.gusto.com/article/999756591000000/set-up-and-manage-time-off-policies-for-admins",
        ],
    },
    {
        "provider": "Personio",
        "source_name": "Personio Help Center - HR Workflows",
        "root_url": "https://support.personio.de/hc/en-us",
        "category": "hr_workflows",
        "source_type": "web_hr_saas_docs",
        "use_map": True,
        "max_depth": 2,
        "max_urls": 20,
        "min_urls": 5,
        "extract_depth": "advanced",
        "keywords": [
            "onboarding",
            "offboarding",
            "absence",
            "employee",
            "approval",
            "roles",
            "permissions",
            "workflow",
            "documents",
            "performance",
        ],
        "seed_urls": [
            "https://support.personio.de/hc/en-us/articles/115002474325-Common-onboarding-templates-and-steps",
        ],
    },
    {
        "provider": "SHRM",
        "source_name": "SHRM HR Policies",
        "root_url": "https://www.shrm.org/topics-tools/tools/policies",
        "category": "hr_policy_reference",
        "source_type": "web_hr_policy_reference",
        "use_map": True,
        "max_depth": 1,
        "max_urls": 15,
        "min_urls": 3,
        "extract_depth": "advanced",
        "keywords": [
            "policy",
            "leave",
            "vacation",
            "sick",
            "benefits",
            "employment",
            "workplace",
            "harassment",
            "overtime",
        ],
        "seed_urls": [
            "https://www.shrm.org/topics-tools/tools/policies",
        ],
    },
]